### PR TITLE
add Set clause support in Sql class

### PR DESCRIPTION
**Pull request by u0hz**
add `Set` clause support in Sql class in `Sql` class that is almost the same like how to use `Where`

### CODE REVIEW

**Comment by pleb** [comment]
@u0hz thanks for the contribute.

**Comment by pleb** [comment]
@u0hz The only concern here is that people may use this and not parameters. Does this open PetaPoco for easier SQL injection attacks? I know with the use of strings, it's already possible, but newcomers may fail to use parameters and may default to this. Thoughts?

**Comment by u0hz** [comment]
Yes, it does have the problem.
Although a `Set(string field,  object value)` function can avoid the problem above, but it's not so in common use. 
And on the other hand, `Where` may have the same problem. So I think the docs should make that point clear, and encourage people to use parameters instead of simply join strings.

**Comment by pleb** [comment]
Good points ;)

**Pull request merged**
