### PR TITLE
refactor(IsNew): check string type PrimaryKey first #538

### PR DESCRIPTION
**Pull request by ArgoZhang**
#Issue
link https://github.com/CollaboratingPlatypus/PetaPoco/issues/538

### CODE REVIEW

**Comment by pleb** [comment]
Hey @ArgoZhang why was this causing an issue? I don't see how this change affects anything.

**Comment by ArgoZhang** [comment]
> Hey @ArgoZhang why was this causing an issue? I don't see how this change affects anything.

```
[TableName("Groups")]
public class Group
{
    public string Id { get; set; }
    public string GroupName { get; set; }

    public void Save(Group poco)
    {
        var db = DbManager.Create();
        db.Save(new Group() { Id = "", GroupName = "UnitTest" });
    }
}
```
because Id value is **String.Empty** not **null**, so IsNew method not work correctly.

**Comment by pleb** [comment]
@ArgoZhang could you please fix the line endings?

**Comment by ArgoZhang** [comment]
@pleb done! resolved the conflicts.
thank you for pick up this PR.
😃

**Pull request merged**
