### PR TITLE
Add Async support

### PR DESCRIPTION
**Pull request by md-frank**
Add Async support

### CODE REVIEW

**Comment by pleb** [comment]
Hi @md-frank, 

Thanks for the PR. However, this isn't how async should be implemented. It should flow through the db provider. 

Thoughts?

**Comment by md-frank** [comment]
For example IExecute.Execute, This is a synchronous method.
The same, Asynchronous version of Execute should be under the IExecute

**Comment by md-frank** [comment]
Hi pleb,
Excuse me for any mistakes since my not-so-good English.

For example IExecute.Execute, This is a synchronous method.
The same, Asynchronous version of Execute should be under the IExecute

**Comment by pflannery** [comment]
Even if `IExecute.ExecuteAsync` is using the asynchronous Task<T> object the synchronous will still problem occur in the database IO calls.

What's really needed for true asynchronous state is that all of the database providers offer their asynchronous IO methods.

I.E. [DbCommand.ExecuteScalarAsync](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.executescalarasync?view=netframework-4.7#System_Data_Common_DbCommand_ExecuteScalarAsync) should be used instead of `DbCommand.ExecuteScalar` when a user wants an asynchronous workflow.

**Comment by pleb** [comment]
@md-frank, thanks for the contribution. 

I'm going to close this because I've added full async support to PP. What I mean by this, is that the async I've added flows all the way to the DB Provider, and hopefully, forms a non-blocking routine, but that is in the hand of the actual provider. 

Thanks. If you need async support, it's currently in the beta build

**Pull request closed without merging**
