### PR TITLE
Add async support

### PR DESCRIPTION
**Pull request by pleb**

### CODE REVIEW

**Comment by pleb** [comment]
Tag #485

**Comment by asherber** [comment]
Wondering if a pattern like this might be useful to reduce code duplication: https://gist.github.com/asherber/8c5eaab9975e393de6ed752a0e30a1cb

See the Flag Argument Hack at https://msdn.microsoft.com/en-us/magazine/mt238404.aspx

**Comment by pleb** [comment]
I had some similar, but .net 4 doesn’t support the async method modifier. So the use of #if becomes an ugly mess

**Comment by asherber** [comment]
Interesting, I wasn't getting a compiler error on that, but when I made a new test app in .NET 4 just to reproduce some of this, it wouldn't run.

Take a look at the gist now.  Not the prettiest, but I suspect it's better than duplicating all that code.

**Comment by pleb** [comment]
At this stage, it's likely that only the connection and query method will be duplicated. We can revisit the connection one later on if we need to. The query will likely always be duplicated, as I could not find a way of making yield work with async. That said, when we can roll c# 8 we can revisit it again, but it probably going to be something that can't be changed due to the language restrictions we have now and that fact it would be a breaking change later on. I looked at how dapper got around it, and well, they just disable the streaming that yield gives and return a pre-populated list, which is effectively the PP fetch method.

**Pull request merged**
