### PR TITLE
Multi part pks

### PR DESCRIPTION
**Pull request by pynej**

### CODE REVIEW

**Comment by Spilarix** [comment]
I really need this evolution to be able to use PetaPoco. Will it be integrated in a few days or later ?

**Comment by pynej** [comment]
ref https://github.com/CollaboratingPlatypus/PetaPoco/issues/330

**Comment by pleb** [comment]
@pynej sorry mate. I've got a few work contracts keeping my busy at the moment. I'll hopefully add a heap of integration tests over the next week or so.

@Spilarix if you need to use it, then go ahead :smile: But, you'll need to clone and build this branch. It'll  be merged when everyone working on it is happy there won't be any regression to the existing code base.

**Comment by pynej** [comment]
@Spilarix Fyi its not actually complete, there is some internals code that is still messed up.

**Comment by pynej** [comment]
Also not, that is is possible to write your own where clauses to work around the issue in the interim.

**Pull request merged**
