### PR TITLE
Allow for an IDbDataParameter to be added directly to Sql

### PR DESCRIPTION
**Pull request by asherber**
I'm not sure how you feel about this. It helps with the issue in #488, but it may be unnecessary or may lead to confusion or misuse. I don't feel strongly about arguing for its inclusion.

### CODE REVIEW

**Comment by pleb** [comment]
Yeah. Hmm. I can see people being confused about what it's used for.

**Comment by pleb** [comment]
Actually, it should be ok and I see it has a purpose.

**Comment by asherber** [comment]
Sorry, this isn't working correctly -- I didn't follow it all the way through. The param is getting added to the Sql, but it's not making it through `CreateCommand()` and getting added to the `IDbCommand`. I'll work on fixing this and get you an updated PR.

**Comment by asherber** [comment]
@pleb This needs further discussion. Should we do that here, or open a new issue?

**Pull request merged**
